### ISSUE TITLE
Convert beatmap error on 

### ISSUE THREAD

**Issue by EverybodyDanceNow** [OliBomby/osu-diffusion#5]
on colab on "Convert Beatmap" step;
python3: can't open file '/content/osu-diffusion/osu-diffusion/osu-diffusion/osu-diffusion/sample.py': [Errno 2] No such file or directory
Beatmap successfully saved to results/668662 Yooh - Ice Angel/668662 result 1451282 0.osu

**Comment by EverybodyDanceNow** [comment]
fixed.

**Comment by u1pvq** [comment]
how did you fix?

**Comment by TheKayneGame** [comment]
Thanks this really helped me!
